### ISSUE TITLE
Please add Pump Duty and Demand Control

### ISSUE THREAD

**Issue by supersjimmie** [kamaradclimber/heishamon-homeassistant#110]
We have some old radiators in our house, which we only need during some times in the winter.
To avoid that the water makes too much noise, we need to change Pump Duty a couple of time per season.

Please make it possible to use:
panasonic_heat_pump/commands/SetMaxPumpDuty

Also, please make Demand Control available?
panasonic_heat_pump/main/SetDemandControl

It can now be done by manual setup (also via heishamon, but manually created in HA)
E.g.:
````
- id: 1264e8eb3ac74d55b1bc5d2bad7ed5c8
  alias: Set pump speed
  trigger:
  - platform: state
    entity_id: input_number.heishamon_pump_speed
  condition: []
  action:
  - delay: '5'
  - service: mqtt.publish
    data_template:
      topic: panasonic_heat_pump/commands/SetMaxPumpDuty
      retain: false
      payload_template: '{{ "%.0f" % (states(''input_number.heishamon_pump_speed'')
        | int) }}'
  mode: single
````
