### ISSUE TITLE
Cooling compensation curve: wrong min/max values

### ISSUE THREAD

**Issue by b3nn0** [kamaradclimber/heishamon-homeassistant#218]
** Versions **

- Home Assistant version (for instance 2023.9): 2024.06
- This integration version (for instance 1.1.0): 1.9.0

**Describe the bug**

Hi,
the min/max values for the entities regarding cooling compensation curve seem to be wrong.
On my heat pump (Aquarea L series 5kw), setting everything to min/max looks like this:
![IMG_20240621_171753](https://github.com/kamaradclimber/heishamon-homeassistant/assets/1858945/d06f3649-3af1-4e5f-a489-9a54b31571e6)
![IMG_20240621_171825](https://github.com/kamaradclimber/heishamon-homeassistant/assets/1858945/a86bf57a-a5ef-4da2-b8be-6791e15037f9)

However, the temperature range I can set in this integration is:
Min and max outside temperature: -20°C to 30°C
Min/max water temperature: 15°C to 60°C

I suppose having larger range (as with the outside temperature) is not beautiful, but not really a problem.
However, only being able to set the min water temperature to 15°C is a bit lacking - in some cases I want to set it lower than that.

**To Reproduce**
Slightly adapted your Heat curve adjustment card to make it easy to test:
```
type: vertical-stack
title: Kühlkurve
cards:
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: entities
            entities:
              - entity: number.panasonic_heat_pump_main_z1_cool_curve_outside_low_temp
              - entity: number.panasonic_heat_pump_main_z1_cool_curve_target_high_temp
      - type: horizontal-stack
        cards:
          - type: entities
            entities:
              - entity: >-
                  number.panasonic_heat_pump_main_z1_cool_curve_outside_high_temp
              - entity: number.panasonic_heat_pump_main_z1_cool_curve_target_low_temp
  - type: custom:plotly-graph
    refresh_interval: 10
    defaults:
      entity:
        show_value: true
        line:
          shape: spline
    layout:
      xaxis:
        type: number
        autorange: true
    entities:
      - entity: ''
        name: Zone 1
        x:
          - >-
            $ex
            hass.states['number.panasonic_heat_pump_main_z1_cool_curve_outside_low_temp'].state
          - >-
            $ex
            hass.states['number.panasonic_heat_pump_main_z1_cool_curve_outside_high_temp'].state
        'y':
          - >-
            $ex
            hass.states['number.panasonic_heat_pump_main_z1_cool_curve_target_high_temp'].state
          - >-
            $ex
            hass.states['number.panasonic_heat_pump_main_z1_cool_curve_target_low_temp'].state
```

**Expected behavior**

It should be possible to set it lower than 15°C

**Screenshots**

![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/1858945/e16716d6-dcbf-427a-9de7-5283bc24b91c)
