### ISSUE TITLE
Add some nice cards to docu

### ISSUE THREAD

**Issue by Skol6** [kamaradclimber/heishamon-homeassistant#259]
Hi.

I have some nice overviews. Maybe you can share the code in your documentation:

Current Values
```
type: entities
entities:
  - entity: sensor.panasonic_heat_pump_main_outside_temp
  - entity: sensor.panasonic_heat_pump_main_room_thermostat_temp
  - entity: sensor.panasonic_heat_pump_main_dhw_temp
  - entity: sensor.panasonic_heat_pump_main_threeway_valve_state
  - entity: switch.panasonic_heat_pump_main_defrosting_state
  - entity: sensor.panasonic_heat_pump_main_main_target_temp
  - entity: sensor.panasonic_heat_pump_main_main_outlet_temp
  - entity: sensor.panasonic_heat_pump_main_main_inlet_temp
  - entity: sensor.panasonic_heat_pump_main_compressor_freq
  - entity: sensor.panasonic_heat_pump_main_high_pressure
  - entity: sensor.panasonic_heat_pump_main_fan1_motor_speed
  - entity: sensor.panasonic_heat_pump_main_pump_flow
  - entity: sensor.panasonic_heat_pump_main_pump_speed
  - entity: sensor.panasonic_heat_pump_main_pump_duty
  - entity: sensor.panasonic_heat_pump_s0_watt_1
  - entity: sensor.panasonic_heat_pump_main_heat_power_consumption
  - entity: sensor.panasonic_heat_pump_cop
  - entity: sensor.aquarea_cop_calc
  - entity: sensor.panasonic_heat_pump_main_operations_counter
  - entity: sensor.panasonic_heat_pump_main_operations_hours
  - entity: sensor.aquarea_average_runtime
title: Aktuelle Werte
state_color: true
```

Current Settings:
```
type: grid
square: false
columns: 1
cards:
  - type: entities
    entities:
      - entity: water_heater.panasonic_heat_pump_main_dhw_target_temp
      - entity: climate.panasonic_heat_pump_main_z1_temp
      - entity: select.panasonic_heat_pump_main_operating_mode_state
      - entity: number.panasonic_heat_pump_main_z1_heat_request_temp
      - entity: number.panasonic_heat_pump_main_max_pump_duty
      - entity: number.panasonic_heat_pump_main_heat_delta
      - entity: number.panasonic_heat_pump_main_dhw_heat_delta
      - entity: number.panasonic_heat_pump_main_heating_off_outdoor_temp
      - entity: number.panasonic_heat_pump_main_z1_heat_curve_target_high_temp
      - entity: number.panasonic_heat_pump_main_z1_heat_curve_target_low_temp
      - entity: number.panasonic_heat_pump_main_z1_heat_curve_outside_low_temp
      - entity: number.panasonic_heat_pump_main_z1_heat_curve_outside_high_temp
      - entity: binary_sensor.panasonic_heat_pump_main_quiet_mode_schedule
      - entity: select.panasonic_heat_pump_main_quiet_mode_level
      - entity: binary_sensor.panasonic_heat_pump_main_dhw_installed
      - entity: binary_sensor.panasonic_heat_pump_main_room_heater_state
      - entity: binary_sensor.panasonic_heat_pump_main_dhw_heater_state
    title: Einstellungen
```

Grafik Cards:
```
type: vertical-stack
cards:
  - type: history-graph
    entities:
      - entity: switch.panasonic_heat_pump_main_heatpump_state
      - entity: select.panasonic_heat_pump_main_operating_mode_state
      - entity: select.panasonic_heat_pump_commands_setsmartgridmode
      - entity: sensor.panasonic_heat_pump_main_threeway_valve_state
      - entity: switch.panasonic_heat_pump_main_defrosting_state
      - entity: binary_sensor.panasonic_heat_pump_main_internal_heater_state
      - entity: select.panasonic_heat_pump_main_quiet_mode_level
      - entity: switch.panasonic_heat_pump_main_holiday_mode_state
    hours_to_show: 24
    title: Status
  - type: history-graph
    entities:
      - entity: sensor.panasonic_heat_pump_main_outside_temp
      - entity: sensor.panasonic_heat_pump_main_room_thermostat_temp
      - entity: number.panasonic_heat_pump_main_z1_heat_request_temp
      - entity: sensor.panasonic_heat_pump_main_dhw_temp
      - entity: sensor.panasonic_heat_pump_main_main_target_temp
      - entity: sensor.panasonic_heat_pump_main_main_outlet_temp
      - entity: sensor.panasonic_heat_pump_main_main_inlet_temp
    title: Temperaturen
    hours_to_show: 24
  - type: history-graph
    entities:
      - sensor.panasonic_heat_pump_main_compressor_freq
    title: Kompressor
    hours_to_show: 24
  - type: history-graph
    entities:
      - sensor.panasonic_heat_pump_main_pump_flow
    title: Volumenstrom
    hours_to_show: 24
  - type: history-graph
    entities:
      - sensor.panasonic_heat_pump_main_pump_speed
      - sensor.panasonic_heat_pump_main_fan1_motor_speed
    title: Drehzahlen
    hours_to_show: 24
  - type: history-graph
    entities:
      - entity: sensor.panasonic_heat_pump_main_pump_duty
      - entity: number.panasonic_heat_pump_main_max_pump_duty
    hours_to_show: 24
  - type: history-graph
    entities:
      - sensor.panasonic_heat_pump_main_dhw_power_consumption
      - sensor.panasonic_heat_pump_main_dhw_power_production
      - sensor.panasonic_heat_pump_main_heat_power_consumption
      - sensor.panasonic_heat_pump_main_heat_power_production
      - sensor.panasonic_heat_pump_s0_watt_1
      - sensor.panasonic_heat_pump_s0_watt_2
      - sensor.aquarea_energy_consumption
      - sensor.aquarea_energy_production
    title: Energie
    hours_to_show: 24
  - type: history-graph
    entities:
      - entity: sensor.panasonic_heat_pump_main_high_pressure
    hours_to_show: 24
  - type: history-graph
    entities:
      - sensor.panasonic_heat_pump_cop
    title: COP
    hours_to_show: 24
  - type: custom:plotly-graph
    refresh_interval: 10
    title: Heat curve
    defaults:
      entity:
        show_value: true
        line:
          shape: spline
    layout:
      xaxis:
        type: number
        autorange: true
    entities:
      - entity: ""
        name: Zone 1
        x:
          - >-
            $ex
            hass.states['number.panasonic_heat_pump_main_z1_heat_curve_outside_low_temp'].state
          - >-
            $ex
            hass.states['number.panasonic_heat_pump_main_z1_heat_curve_outside_high_temp'].state
        "y":
          - >-
            $ex
            hass.states['number.panasonic_heat_pump_main_z1_heat_curve_target_high_temp'].state
          - >-
            $ex
            hass.states['number.panasonic_heat_pump_main_z1_heat_curve_target_low_temp'].state
grid_options:
  columns: full
```
