### ISSUE TITLE
New Heat Curve chart with shift Temp and crosshair for the actual values

### ISSUE THREAD

**Issue by thecem** [kamaradclimber/heishamon-homeassistant#268]
Since ther is no discussion for this:

![grafik](https://github.com/user-attachments/assets/f13d69e9-46cd-4dde-8995-092d008e05df)

<details>
  <summary>config</summary>

```
type: grid
cards:
  - type: heading
    heading_style: title
    heading: Heat Curve
    icon: mdi:chart-bell-curve-cumulative
    badges:
      - type: entity
        show_state: true
        show_icon: true
        entity: sensor.panasonic_heat_pump_main_outside_temp
        icon: mdi:home-thermometer-outline
        tap_action:
          action: more-info
      - type: entity
        show_state: true
        show_icon: true
        entity: number.panasonic_heat_pump_main_z1_heat_curve_outside_low_temp
        icon: mdi:thermometer-chevron-down
        tap_action:
          action: more-info
      - type: entity
        show_state: true
        show_icon: false
        entity: number.panasonic_heat_pump_main_z1_heat_curve_target_high_temp
        icon: mdi:thermometer-chevron-down
        tap_action:
          action: more-info
      - type: entity
        show_state: true
        show_icon: true
        entity: number.panasonic_heat_pump_main_z1_heat_curve_outside_high_temp
        icon: mdi:thermometer-chevron-up
        tap_action:
          action: more-info
      - type: entity
        show_state: true
        show_icon: false
        entity: number.panasonic_heat_pump_main_z1_heat_curve_target_low_temp
        icon: mdi:thermometer-chevron-up
        tap_action:
          action: more-info
  - type: custom:plotly-graph
    refresh_interval: 10
    defaults:
      entity:
        line:
          shape: spline
    layout:
      xaxis:
        type: number
        autorange: true
    entities:
      - entity: ""
        name: >
          $ex "Water Target Temp " +
          hass.states["sensor.panasonic_heat_pump_main_main_target_temp"].state
          + "°C"
        line:
          width: 1
          dash: dot
        x:
          - >-
            $ex
            hass.states['number.panasonic_heat_pump_main_z1_heat_curve_outside_low_temp'].state
          - >-
            $ex
            hass.states['number.panasonic_heat_pump_main_z1_heat_curve_outside_high_temp'].state
        "y":
          - >-
            $ex
            hass.states['sensor.panasonic_heat_pump_main_main_target_temp'].state
          - >-
            $ex
            hass.states['sensor.panasonic_heat_pump_main_main_target_temp'].state
      - entity: ""
        name: >
          $ex "Outside Temp " +
          hass.states["sensor.panasonic_heat_pump_main_outside_temp"].state +
          "°C"
        value: "1"
        line:
          width: 1
          dash: dot
        x:
          - >-
            $ex
            hass.states['sensor.panasonic_heat_pump_main_outside_temp'].state
          - >-
            $ex
            hass.states['sensor.panasonic_heat_pump_main_outside_temp'].state
        "y":
          - >-
            $ex
            hass.states['number.panasonic_heat_pump_main_z1_heat_curve_target_high_temp'].state
          - >-
            $ex
            parseFloat(hass.states['number.panasonic_heat_pump_main_z1_heat_curve_target_low_temp'].state)
            +
            parseFloat(hass.states['number.panasonic_heat_pump_main_z1_heat_request_temp'].state)
      - entity: ""
        name: >
          $ex "Zone 1 (with request shift of " +
          hass.states["number.panasonic_heat_pump_main_z1_heat_request_temp"].state
          + "°C" + ")"
        x:
          - >-
            $ex
            hass.states['number.panasonic_heat_pump_main_z1_heat_curve_outside_low_temp'].state
          - >-
            $ex
            hass.states['number.panasonic_heat_pump_main_z1_heat_curve_outside_high_temp'].state
        "y":
          - >-
            $ex
            parseFloat(hass.states['number.panasonic_heat_pump_main_z1_heat_curve_target_high_temp'].state)
            +
            parseFloat(hass.states['number.panasonic_heat_pump_main_z1_heat_request_temp'].state)
          - >-
            $ex
            parseFloat(hass.states['number.panasonic_heat_pump_main_z1_heat_curve_target_low_temp'].state)
            +
            parseFloat(hass.states['number.panasonic_heat_pump_main_z1_heat_request_temp'].state)
      - entity: ""
        name: Zone 1
        x:
          - >-
            $ex
            hass.states['number.panasonic_heat_pump_main_z1_heat_curve_outside_low_temp'].state
          - >-
            $ex
            hass.states['number.panasonic_heat_pump_main_z1_heat_curve_outside_high_temp'].state
        "y":
          - >-
            $ex
            hass.states['number.panasonic_heat_pump_main_z1_heat_curve_target_high_temp'].state
          - >-
            $ex
            hass.states['number.panasonic_heat_pump_main_z1_heat_curve_target_low_temp'].state
  - type: tile
    entity: sensor.panasonic_heat_pump_main_outside_temp
    name: Outdoor Temp
  - type: tile
    entity: number.panasonic_heat_pump_main_z1_heat_request_temp
    name: Reqested shift
  - type: tile
    entity: number.panasonic_heat_pump_main_z1_heat_curve_target_high_temp
    name: Water min
  - type: tile
    entity: number.panasonic_heat_pump_main_z1_heat_curve_target_low_temp
    name: Water max
  - type: tile
    entity: number.panasonic_heat_pump_main_z1_heat_curve_outside_low_temp
    name: Out Air min
  - type: tile
    entity: number.panasonic_heat_pump_main_z1_heat_curve_outside_high_temp
    name: Out Air max
```
</details>
